name: ace0
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - alsa-lib
  - appdirs
  - blas
  - blosc
  - brotli
  - brotli-bin
  - brotlipy
  - brunsli
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - cfitsio
  - charls
  - charset-normalizer
  - cloudpickle
  - contourpy
  - cryptography
  - cuda-cudart
  - cuda-cupti
  - cuda-libraries
  - cuda-nvrtc
  - cuda-nvtx
  - cuda-runtime
  - cycler
  - cytoolz
  - dask-core
  - dataclasses
  - dbus
  - expat
  - ffmpeg
  - filelock
  - flit-core
  - fontconfig
  - fonttools
  - freetype
  - freetype-py
  - fsspec
  - future
  - gettext
  - giflib
  - glib
  - glib-tools
  - gmp
  - gmpy2
  - gnutls
  - graphite2
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - hdf5
  - icu
  - idna
  - imagecodecs-lite
  - imageio
  - importlib_resources
  - intel-openmp
  - jasper
  - jinja2
  - joblib
  - jpeg
  - jxrlib
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libaec
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libclang
  - libcublas
  - libcufft
  - libcufile
  - libcurand
  - libcurl
  - libcusolver
  - libcusparse
  - libdeflate
  - libedit
  - libev
  - libevent
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libglu
  - libgomp
  - libiconv
  - libidn2
  - liblapack
  - liblapacke
  - libllvm11
  - libnghttp2
  - libnpp
  - libnvjpeg
  - libogg
  - libopencv
  - libopus
  - libpng
  - libpq
  - libssh2
  - libstdcxx-ng
  - libtasn1
  - libtiff
  - libunistring
  - libuuid
  - libvorbis
  - libwebp
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libzopfli
  - locket
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpc
  - mpfr
  - mpmath
  - munkres
  - mysql-common
  - mysql-libs
  - ncurses
  - nettle
  - networkx
  - nspr
  - nss
  - numpy
  - numpy-base
  - opencv
  - openh264
  - openjpeg
  - openssl
  - packaging
  - partd
  - pcre
  - pillow
  - pip
  - pixman
  - pooch
  - pthread-stubs
  - py-opencv
  - pycparser
  - pyglet
  - pyopengl
  - pyopenssl
  - pyparsing
  - pyqt
  - pyrender
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pytorch
  - pytorch-cuda
  - pytorch-mutex
  - pywavelets
  - pyyaml
  - qt
  - readline
  - requests
  - scikit-image
  - scipy
  - setuptools
  - six
  - snappy
  - sqlite
  - sympy
  - tifffile
  - tk
  - toolz
  - torchaudio
  - torchtriton
  - torchvision
  - tornado
  - trimesh
  - typing_extensions
  - urllib3
  - wheel
  - x264
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - zfp
  - zipp
  - zlib
  - zstd
  - pip:
      - pyqt5-sip
      - pyqtchart
      - pyqtwebengine
      - roma
      - timm
      - pycolmap